name: Weekly PR Reminder Emails

on:
  schedule:
    # Weekly personalised reminders: Mondays at 09:00 UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

env:
  # Contributor emails from secrets
  EMAIL_schyen: ${{ secrets.EMAIL_schyen }}
  EMAIL_devGuy42: ${{ secrets.EMAIL_devGuy42 }}
  # Add more contributors here

jobs:
  collect-prs:
    runs-on: ubuntu-latest
    outputs:
      assigneeMap: ${{ steps.collect.outputs.assigneeMap }}
    steps:
      - name: Collect PRs and assignment dates
        id: collect
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            
            // Get all open PRs
            const pulls = await github.paginate(github.rest.pulls.list, {
              owner,
              repo,
              state: "open",
              per_page: 100
            });

            if (pulls.length === 0) {
              console.log("No open PRs, skipping workflow");
              core.setOutput("assigneeMap", "{}");
              return;
            }

            const assigneeMap = {};
            for (const pr of pulls) {
              if (pr.assignees.length === 0) continue;

              const { data: events } = await github.request(
                "GET /repos/{owner}/{repo}/issues/{issue_number}/timeline",
                {
                  owner,
                  repo,
                  issue_number: pr.number,
                  headers: { accept: "application/vnd.github.mockingbird-preview+json" }
                }
              );

              for (const assignee of pr.assignees) {
                let assignedDate = null;
                for (const ev of events) {
                  if (ev.event === "assigned" && ev.assignee?.login === assignee.login) {
                    assignedDate = ev.created_at;
                  }
                }

                if (!assigneeMap[assignee.login]) {
                  assigneeMap[assignee.login] = [];
                }

                assigneeMap[assignee.login].push({
                  number: pr.number,
                  title:
