name: Test Email

on:
  workflow_dispatch:   # lets you trigger manually from the Actions tab

jobs:
  send-test:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "✅ GitHub Actions Email Test"
          to: ${{ secrets.EMAIL_schyen }}
          from: "github-actions@${{ github.repository }}"
          body: |
            Hello 👋,

            This is a test email sent from GitHub Actions using your SMTP settings.
            
            If you received this, your configuration works! 🎉
