name: Validate PR Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  validate-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Validate labels (require exactly one of: feat, fix, break)
        run: |
          labels_json='${{ toJson(github.event.pull_request.labels) }}'
          echo "Labels JSON: $labels_json"
      
          # Extract all special labels from JSON (match name field only)
          special_labels=$(echo "$labels_json" | grep -o '"name":"[^"]*"' | grep -E '"name":"(feat|fix|break)"' | wc -l)
          
          echo "Found $special_labels special label(s)"
      
          if [ "$special_labels" -eq 1 ]; then
            echo "✅ Exactly one valid label (feat/fix/break) found."
          else
            echo "❌ PR must have exactly one of: feat, fix, or break. Found $special_labels."
            exit 1
          fi
