name: Validate PR Labels

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  validate-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for exactly one of: fix, feat, break
        run: |
          labels_json="${{ toJson(github.event.pull_request.labels) }}"
          echo "Labels JSON: $labels_json"

          special_count=$(echo "$labels_json" | grep -o '"name":"[^"]*"' | grep -E '"name":"(fix|feat|break)"' | wc -l)
          echo "Found $special_count special label(s)"

          if [ "$special_count" -eq 1 ]; then
            echo "✅ Exactly one valid label found."
          else
            echo "❌ PR must have exactly one of: fix, feat, or break."
            exit 1
          fi
